{
  "patch_version": "1.0.0",
  "manager_versions": ["4.1.1.1"],
  "community": false,
  "premium": true,
  "patches": [
    {
      "patch_file": "4111_cluster_reliability_database",
      "md5sum": "04e4d7b9bbb811b2533539feac2d787c",
      "destinations": ["/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/database.py"]
    },
    {
      "patch_file": "4111_cluster_reliability_watch_handlers",
      "md5sum": "371618a8bde3574bae5c75b14d3d6ffc",
      "destinations": ["/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/watch_handlers.py"]
    },
    {
      "patch_file": "4111_cluster_reliability_checks",
      "md5sum": "554f436a8bdc89fa96e6333e4af428b9",
      "destinations": ["/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/checks.py"]
    }
  ],
  "affected_services": [
    "cloudify-handler-runner",
    "cloudify-check-runner"
  ],
  "md5sums_before": {
    "/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/database.py": ["9813eb031ce8bf8933be65a188265e6e"],
    "/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/checks.py": ["b1a0ee973d88851142a56603cf3254c6"],
    "/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/watch_handlers.py": ["0c1ba29e45960b95a4e5e649edfdac6c"]
  },
  "md5sums_after": {
    "/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/database.py": ["62d6f617aede6c57d44e5094951ed74e"],
    "/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/checks.py": ["cae01fa05d59d791c69cf4548b829073"],
    "/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/watch_handlers.py": ["f3226ebe81505eca311469dea1d139d6"]
  }
}
