{
  "patch_version": "1.0.0",
  "manager_versions": ["4.1.1.1"],
  "community": false,
  "premium": true,
  "patches": [
    {
      "patch_file": "clusterdataloss_database",
      "md5sum": "7b48bc4679afe33747dc3336c255e956",
      "destinations": ["/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/database.py"]
    },
    {
      "patch_file": "clusterdataloss_sudo_trampoline",
      "md5sum": "c4a00494053c16f2257351c47cad6274",
      "destinations": ["/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/resources/sudo_trampoline.py",
                       "/opt/cloudify/sudo_trampoline.py"]
    }
  ],
  "affected_services": [
    "cloudify-handler-runner"
  ],
  "md5sums_before": {
    "/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/database.py": ["acdddd64303c976bb4f0c47e1ff0ef5b"],
    "/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/resources/sudo_trampoline.py": ["774e91145b7262f3c0367524085efd45"],
    "/opt/cloudify/sudo_trampoline.py": ["774e91145b7262f3c0367524085efd45"]
  },
  "md5sums_after": {
    "/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/database.py": ["9813eb031ce8bf8933be65a188265e6e"],
    "/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/resources/sudo_trampoline.py": ["695af4b1904d1237c38e77fd453fc33d"],
    "/opt/cloudify/sudo_trampoline.py": ["695af4b1904d1237c38e77fd453fc33d"]
  }
}
