{
  "patch_version": "1.0.0",
  "manager_versions": ["4.5.0","4.5"],
  "community": true,
  "premium": true,
  "patches": [
    {
      "patch_file": "cluster_join_ssl_oserror",
      "md5sum": "812930de2c7d1f850a6193a17bf2d8c3",
      "destinations": ["/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/ssl.py"]
    }
  ],
  "affected_services": [],
  "md5sums_before": {
    "/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/ssl.py": ["1202dae96cffff97b46541751fc70ade"]
  },
  "md5sums_after": {
    "/opt/manager/env/lib/python2.7/site-packages/cloudify_premium/ha/ssl.py": ["a2e81adfc303365f0dfc38fc54ce5d6e"]
  }
}
